delete from planet_climates;
delete from planet_terrains;
delete from climates;
delete from terrains;
delete from planets;

insert into climates (id, climate_name) values (1, 'temperate');
insert into climates (id, climate_name) values (2, 'tropical');
insert into climates (id, climate_name) values (3, 'frozen');
insert into climates (id, climate_name) values (4, 'murky');
insert into climates (id, climate_name) values (5, 'arid');
insert into climates (id, climate_name) values (6, 'windy');
insert into climates (id, climate_name) values (7, 'hot');
insert into climates (id, climate_name) values (8, 'artificial temperate');
insert into climates (id, climate_name) values (9, 'frigid');
insert into climates (id, climate_name) values (10, 'humid');
insert into climates (id, climate_name) values (11, 'moist');
insert into climates (id, climate_name) values (12, 'polluted');
insert into climates (id, climate_name) values (13, '');
insert into climates (id, climate_name) values (14, 'superheated');
insert into climates (id, climate_name) values (15, 'subartic');
insert into climates (id, climate_name) values (16, 'artic');
insert into climates (id, climate_name) values (17, 'rocky');
insert into terrains (id, terrain_name) values (1, 'grasslands');
insert into terrains (id, terrain_name) values (2, 'mountains');
insert into terrains (id, terrain_name) values (3, 'jungle');
insert into terrains (id, terrain_name) values (4, 'rainforests');
insert into terrains (id, terrain_name) values (5, 'tundra');
insert into terrains (id, terrain_name) values (6, 'ice caves');
insert into terrains (id, terrain_name) values (7, 'mountain ranges');
insert into terrains (id, terrain_name) values (8, 'swamp');
insert into terrains (id, terrain_name) values (9, 'jungles');
insert into terrains (id, terrain_name) values (10, 'gas giant');
insert into terrains (id, terrain_name) values (11, 'forests');
insert into terrains (id, terrain_name) values (12, 'lakes');
insert into terrains (id, terrain_name) values (13, 'grassy hills');
insert into terrains (id, terrain_name) values (14, 'swamps');
insert into terrains (id, terrain_name) values (15, 'cityscape');
insert into terrains (id, terrain_name) values (16, 'ocean');
insert into terrains (id, terrain_name) values (17, 'rock');
insert into terrains (id, terrain_name) values (18, 'desert');
insert into terrains (id, terrain_name) values (19, 'mountain');
insert into terrains (id, terrain_name) values (20, 'barren');
insert into terrains (id, terrain_name) values (21, 'scrublands');
insert into terrains (id, terrain_name) values (22, 'savanna');
insert into terrains (id, terrain_name) values (23, 'canyons');
insert into terrains (id, terrain_name) values (24, 'sinkholes');
insert into terrains (id, terrain_name) values (25, 'volcanoes');
insert into terrains (id, terrain_name) values (26, 'lava rivers');
insert into terrains (id, terrain_name) values (27, 'caves');
insert into terrains (id, terrain_name) values (28, 'rivers');
insert into terrains (id, terrain_name) values (29, 'airless asteroid');
insert into terrains (id, terrain_name) values (30, 'glaciers');
insert into terrains (id, terrain_name) values (31, 'ice canyons');
insert into terrains (id, terrain_name) values (32, 'fungus forests');
insert into terrains (id, terrain_name) values (33, 'fields');
insert into terrains (id, terrain_name) values (34, 'rock arches');
insert into terrains (id, terrain_name) values (35, 'grass');
insert into terrains (id, terrain_name) values (36, 'plains');
insert into terrains (id, terrain_name) values (37, 'urban');
insert into terrains (id, terrain_name) values (38, 'hills');
insert into terrains (id, terrain_name) values (39, 'oceans');
insert into terrains (id, terrain_name) values (40, 'bogs');
insert into terrains (id, terrain_name) values (41, 'savannas');
insert into terrains (id, terrain_name) values (42, 'rocky islands');
insert into terrains (id, terrain_name) values (43, 'seas');
insert into terrains (id, terrain_name) values (44, 'mesas');
insert into terrains (id, terrain_name) values (45, '');
insert into terrains (id, terrain_name) values (46, 'deserts');
insert into terrains (id, terrain_name) values (47, 'reefs');
insert into terrains (id, terrain_name) values (48, 'islands');
insert into terrains (id, terrain_name) values (49, 'rocky deserts');
insert into terrains (id, terrain_name) values (50, 'valleys');
insert into terrains (id, terrain_name) values (51, 'ash');
insert into terrains (id, terrain_name) values (52, 'toxic cloudsea');
insert into terrains (id, terrain_name) values (53, 'plateaus');
insert into terrains (id, terrain_name) values (54, 'verdant');
insert into terrains (id, terrain_name) values (55, 'rocky canyons');
insert into terrains (id, terrain_name) values (56, 'acid pools');
insert into terrains (id, terrain_name) values (57, 'rocky');
insert into terrains (id, terrain_name) values (58, 'vines');
insert into terrains (id, terrain_name) values (59, 'cities');
insert into terrains (id, terrain_name) values (60, 'savannahs');
insert into terrains (id, terrain_name) values (61, 'cliffs');
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (1, 'Alderaan', 24, 364, 12500, 1, 40, 2000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (1, 1);
insert into planet_terrains(planet_idx, terrain_idx) values (1, 2);
insert into planet_climates(planet_idx, climate_idx) values (1, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (2, 'Yavin IV', 24, 4818, 10200, 1, 8, 1000);
insert into planet_terrains(planet_idx, terrain_idx) values (2, 3);
insert into planet_terrains(planet_idx, terrain_idx) values (2, 4);
insert into planet_climates(planet_idx, climate_idx) values (2, 1);
insert into planet_climates(planet_idx, climate_idx) values (2, 2);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (3, 'Hoth', 23, 549, 7200, 1.1, 100, null);
insert into planet_terrains(planet_idx, terrain_idx) values (3, 5);
insert into planet_terrains(planet_idx, terrain_idx) values (3, 6);
insert into planet_terrains(planet_idx, terrain_idx) values (3, 7);
insert into planet_climates(planet_idx, climate_idx) values (3, 3);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (4, 'Dagobah', 23, 341, 8900, null, 8, null);
insert into planet_terrains(planet_idx, terrain_idx) values (4, 8);
insert into planet_terrains(planet_idx, terrain_idx) values (4, 9);
insert into planet_climates(planet_idx, climate_idx) values (4, 4);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (5, 'Bespin', 12, 5110, 118000, 1.5, 0, 6000000);
insert into planet_terrains(planet_idx, terrain_idx) values (5, 10);
insert into planet_climates(planet_idx, climate_idx) values (5, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (6, 'Endor', 18, 402, 4900, 0.85, 8, 30000000);
insert into planet_terrains(planet_idx, terrain_idx) values (6, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (6, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (6, 12);
insert into planet_climates(planet_idx, climate_idx) values (6, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (7, 'Naboo', 26, 312, 12120, 1, 12, 4500000000);
insert into planet_terrains(planet_idx, terrain_idx) values (7, 13);
insert into planet_terrains(planet_idx, terrain_idx) values (7, 14);
insert into planet_terrains(planet_idx, terrain_idx) values (7, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (7, 2);
insert into planet_climates(planet_idx, climate_idx) values (7, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (8, 'Coruscant', 24, 368, 12240, 1, null, 1000000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (8, 15);
insert into planet_terrains(planet_idx, terrain_idx) values (8, 2);
insert into planet_climates(planet_idx, climate_idx) values (8, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (9, 'Kamino', 27, 463, 19720, 1, 100, 1000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (9, 16);
insert into planet_climates(planet_idx, climate_idx) values (9, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (10, 'Geonosis', 30, 256, 11370, 0.9, 5, 100000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (10, 17);
insert into planet_terrains(planet_idx, terrain_idx) values (10, 18);
insert into planet_terrains(planet_idx, terrain_idx) values (10, 19);
insert into planet_terrains(planet_idx, terrain_idx) values (10, 20);
insert into planet_climates(planet_idx, climate_idx) values (10, 1);
insert into planet_climates(planet_idx, climate_idx) values (10, 5);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (11, 'Utapau', 27, 351, 12900, 1, 0.9, 95000000);
insert into planet_terrains(planet_idx, terrain_idx) values (11, 21);
insert into planet_terrains(planet_idx, terrain_idx) values (11, 22);
insert into planet_terrains(planet_idx, terrain_idx) values (11, 23);
insert into planet_terrains(planet_idx, terrain_idx) values (11, 24);
insert into planet_climates(planet_idx, climate_idx) values (11, 1);
insert into planet_climates(planet_idx, climate_idx) values (11, 5);
insert into planet_climates(planet_idx, climate_idx) values (11, 6);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (12, 'Mustafar', 36, 412, 4200, 1, 0, 20000);
insert into planet_terrains(planet_idx, terrain_idx) values (12, 25);
insert into planet_terrains(planet_idx, terrain_idx) values (12, 26);
insert into planet_terrains(planet_idx, terrain_idx) values (12, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (12, 27);
insert into planet_climates(planet_idx, climate_idx) values (12, 7);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (13, 'Kashyyyk', 26, 381, 12765, 1, 60, 45000000);
insert into planet_terrains(planet_idx, terrain_idx) values (13, 3);
insert into planet_terrains(planet_idx, terrain_idx) values (13, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (13, 12);
insert into planet_terrains(planet_idx, terrain_idx) values (13, 28);
insert into planet_climates(planet_idx, climate_idx) values (13, 2);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (14, 'Polis Massa', 24, 590, 0, 0.56, 0, 1000000);
insert into planet_terrains(planet_idx, terrain_idx) values (14, 29);
insert into planet_climates(planet_idx, climate_idx) values (14, 8);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (15, 'Mygeeto', 12, 167, 10088, 1, null, 19000000);
insert into planet_terrains(planet_idx, terrain_idx) values (15, 30);
insert into planet_terrains(planet_idx, terrain_idx) values (15, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (15, 31);
insert into planet_climates(planet_idx, climate_idx) values (15, 9);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (16, 'Felucia', 34, 231, 9100, 0.75, null, 8500000);
insert into planet_terrains(planet_idx, terrain_idx) values (16, 32);
insert into planet_climates(planet_idx, climate_idx) values (16, 7);
insert into planet_climates(planet_idx, climate_idx) values (16, 10);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (17, 'Cato Neimoidia', 25, 278, 0, 1, null, 10000000);
insert into planet_terrains(planet_idx, terrain_idx) values (17, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (17, 33);
insert into planet_terrains(planet_idx, terrain_idx) values (17, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (17, 34);
insert into planet_climates(planet_idx, climate_idx) values (17, 1);
insert into planet_climates(planet_idx, climate_idx) values (17, 11);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (18, 'Saleucami', 26, 392, 14920, null, null, 1400000000);
insert into planet_terrains(planet_idx, terrain_idx) values (18, 27);
insert into planet_terrains(planet_idx, terrain_idx) values (18, 18);
insert into planet_terrains(planet_idx, terrain_idx) values (18, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (18, 25);
insert into planet_climates(planet_idx, climate_idx) values (18, 7);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (19, 'Stewjon', null, null, 0, 1, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (19, 35);
insert into planet_climates(planet_idx, climate_idx) values (19, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (20, 'Eriadu', 24, 360, 13490, 1, null, 22000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (20, 15);
insert into planet_climates(planet_idx, climate_idx) values (20, 12);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (21, 'Corellia', 25, 329, 11000, 1, 70, 3000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (21, 36);
insert into planet_terrains(planet_idx, terrain_idx) values (21, 37);
insert into planet_terrains(planet_idx, terrain_idx) values (21, 38);
insert into planet_terrains(planet_idx, terrain_idx) values (21, 11);
insert into planet_climates(planet_idx, climate_idx) values (21, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (22, 'Rodia', 29, 305, 7549, 1, 60, 1300000000);
insert into planet_terrains(planet_idx, terrain_idx) values (22, 9);
insert into planet_terrains(planet_idx, terrain_idx) values (22, 39);
insert into planet_terrains(planet_idx, terrain_idx) values (22, 37);
insert into planet_terrains(planet_idx, terrain_idx) values (22, 14);
insert into planet_climates(planet_idx, climate_idx) values (22, 7);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (23, 'Nal Hutta', 87, 413, 12150, 1, null, 7000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (23, 37);
insert into planet_terrains(planet_idx, terrain_idx) values (23, 39);
insert into planet_terrains(planet_idx, terrain_idx) values (23, 14);
insert into planet_terrains(planet_idx, terrain_idx) values (23, 40);
insert into planet_climates(planet_idx, climate_idx) values (23, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (24, 'Dantooine', 25, 378, 9830, 1, null, 1000);
insert into planet_terrains(planet_idx, terrain_idx) values (24, 39);
insert into planet_terrains(planet_idx, terrain_idx) values (24, 41);
insert into planet_terrains(planet_idx, terrain_idx) values (24, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (24, 1);
insert into planet_climates(planet_idx, climate_idx) values (24, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (25, 'Bestine IV', 26, 680, 6400, null, 98, 62000000);
insert into planet_terrains(planet_idx, terrain_idx) values (25, 42);
insert into planet_terrains(planet_idx, terrain_idx) values (25, 39);
insert into planet_climates(planet_idx, climate_idx) values (25, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (26, 'Ord Mantell', 26, 334, 14050, 1, 10, 4000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (26, 36);
insert into planet_terrains(planet_idx, terrain_idx) values (26, 43);
insert into planet_terrains(planet_idx, terrain_idx) values (26, 44);
insert into planet_climates(planet_idx, climate_idx) values (26, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (27, 'NA', 0, 0, 0, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (27, 45);
insert into planet_climates(planet_idx, climate_idx) values (27, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (28, 'Trandosha', 25, 371, 0, 0.62, null, 42000000);
insert into planet_terrains(planet_idx, terrain_idx) values (28, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (28, 43);
insert into planet_terrains(planet_idx, terrain_idx) values (28, 1);
insert into planet_terrains(planet_idx, terrain_idx) values (28, 46);
insert into planet_climates(planet_idx, climate_idx) values (28, 5);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (29, 'Socorro', 20, 326, 0, 1, null, 300000000);
insert into planet_terrains(planet_idx, terrain_idx) values (29, 46);
insert into planet_terrains(planet_idx, terrain_idx) values (29, 2);
insert into planet_climates(planet_idx, climate_idx) values (29, 5);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (30, 'Mon Cala', 21, 398, 11030, 1, 100, 27000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (30, 39);
insert into planet_terrains(planet_idx, terrain_idx) values (30, 47);
insert into planet_terrains(planet_idx, terrain_idx) values (30, 48);
insert into planet_climates(planet_idx, climate_idx) values (30, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (31, 'Chandrila', 20, 368, 13500, 1, 40, 1200000000);
insert into planet_terrains(planet_idx, terrain_idx) values (31, 36);
insert into planet_terrains(planet_idx, terrain_idx) values (31, 11);
insert into planet_climates(planet_idx, climate_idx) values (31, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (32, 'Sullust', 20, 263, 12780, 1, 5, 18500000000);
insert into planet_terrains(planet_idx, terrain_idx) values (32, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (32, 25);
insert into planet_terrains(planet_idx, terrain_idx) values (32, 49);
insert into planet_climates(planet_idx, climate_idx) values (32, 14);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (33, 'Toydaria', 21, 184, 7900, 1, null, 11000000);
insert into planet_terrains(planet_idx, terrain_idx) values (33, 14);
insert into planet_terrains(planet_idx, terrain_idx) values (33, 12);
insert into planet_climates(planet_idx, climate_idx) values (33, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (34, 'Malastare', 26, 201, 18880, 1.56, null, 2000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (34, 14);
insert into planet_terrains(planet_idx, terrain_idx) values (34, 46);
insert into planet_terrains(planet_idx, terrain_idx) values (34, 9);
insert into planet_terrains(planet_idx, terrain_idx) values (34, 2);
insert into planet_climates(planet_idx, climate_idx) values (34, 5);
insert into planet_climates(planet_idx, climate_idx) values (34, 1);
insert into planet_climates(planet_idx, climate_idx) values (34, 2);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (35, 'Dathomir', 24, 491, 10480, 0.9, null, 5200);
insert into planet_terrains(planet_idx, terrain_idx) values (35, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (35, 46);
insert into planet_terrains(planet_idx, terrain_idx) values (35, 41);
insert into planet_climates(planet_idx, climate_idx) values (35, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (36, 'Ryloth', 30, 305, 10600, 1, 5, 1500000000);
insert into planet_terrains(planet_idx, terrain_idx) values (36, 2);
insert into planet_terrains(planet_idx, terrain_idx) values (36, 50);
insert into planet_terrains(planet_idx, terrain_idx) values (36, 46);
insert into planet_terrains(planet_idx, terrain_idx) values (36, 5);
insert into planet_climates(planet_idx, climate_idx) values (36, 1);
insert into planet_climates(planet_idx, climate_idx) values (36, 5);
insert into planet_climates(planet_idx, climate_idx) values (36, 15);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (37, 'Aleen Minor', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (37, 45);
insert into planet_climates(planet_idx, climate_idx) values (37, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (38, 'Vulpter', 22, 391, 14900, 1, null, 421000000);
insert into planet_terrains(planet_idx, terrain_idx) values (38, 37);
insert into planet_terrains(planet_idx, terrain_idx) values (38, 20);
insert into planet_climates(planet_idx, climate_idx) values (38, 1);
insert into planet_climates(planet_idx, climate_idx) values (38, 16);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (39, 'Troiken', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (39, 18);
insert into planet_terrains(planet_idx, terrain_idx) values (39, 5);
insert into planet_terrains(planet_idx, terrain_idx) values (39, 4);
insert into planet_terrains(planet_idx, terrain_idx) values (39, 2);
insert into planet_climates(planet_idx, climate_idx) values (39, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (40, 'Tund', 48, 1770, 12190, null, null, 0);
insert into planet_terrains(planet_idx, terrain_idx) values (40, 20);
insert into planet_terrains(planet_idx, terrain_idx) values (40, 51);
insert into planet_climates(planet_idx, climate_idx) values (40, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (41, 'Haruun Kal', 25, 383, 10120, 0.98, null, 705300);
insert into planet_terrains(planet_idx, terrain_idx) values (41, 52);
insert into planet_terrains(planet_idx, terrain_idx) values (41, 53);
insert into planet_terrains(planet_idx, terrain_idx) values (41, 25);
insert into planet_climates(planet_idx, climate_idx) values (41, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (42, 'Cerea', 27, 386, null, 1, 20, 450000000);
insert into planet_terrains(planet_idx, terrain_idx) values (42, 54);
insert into planet_climates(planet_idx, climate_idx) values (42, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (43, 'Glee Anselm', 33, 206, 15600, 1, 80, 500000000);
insert into planet_terrains(planet_idx, terrain_idx) values (43, 12);
insert into planet_terrains(planet_idx, terrain_idx) values (43, 48);
insert into planet_terrains(planet_idx, terrain_idx) values (43, 14);
insert into planet_terrains(planet_idx, terrain_idx) values (43, 43);
insert into planet_climates(planet_idx, climate_idx) values (43, 2);
insert into planet_climates(planet_idx, climate_idx) values (43, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (44, 'Iridonia', 29, 413, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (44, 55);
insert into planet_terrains(planet_idx, terrain_idx) values (44, 56);
insert into planet_climates(planet_idx, climate_idx) values (44, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (45, 'Tholoth', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (45, 45);
insert into planet_climates(planet_idx, climate_idx) values (45, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (46, 'Iktotch', 22, 481, null, 1, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (46, 57);
insert into planet_climates(planet_idx, climate_idx) values (46, 5);
insert into planet_climates(planet_idx, climate_idx) values (46, 17);
insert into planet_climates(planet_idx, climate_idx) values (46, 6);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (47, 'Quermia', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (47, 45);
insert into planet_climates(planet_idx, climate_idx) values (47, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (48, 'Dorin', 22, 409, 13400, 1, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (48, 45);
insert into planet_climates(planet_idx, climate_idx) values (48, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (49, 'Champala', 27, 318, null, 1, null, 3500000000);
insert into planet_terrains(planet_idx, terrain_idx) values (49, 39);
insert into planet_terrains(planet_idx, terrain_idx) values (49, 4);
insert into planet_terrains(planet_idx, terrain_idx) values (49, 53);
insert into planet_climates(planet_idx, climate_idx) values (49, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (50, 'Mirial', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (50, 46);
insert into planet_climates(planet_idx, climate_idx) values (50, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (51, 'Serenno', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (51, 4);
insert into planet_terrains(planet_idx, terrain_idx) values (51, 28);
insert into planet_terrains(planet_idx, terrain_idx) values (51, 2);
insert into planet_climates(planet_idx, climate_idx) values (51, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (52, 'Concord Dawn', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (52, 9);
insert into planet_terrains(planet_idx, terrain_idx) values (52, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (52, 46);
insert into planet_climates(planet_idx, climate_idx) values (52, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (53, 'Zolan', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (53, 45);
insert into planet_climates(planet_idx, climate_idx) values (53, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (54, 'Ojom', null, null, null, null, 100, 500000000);
insert into planet_terrains(planet_idx, terrain_idx) values (54, 39);
insert into planet_terrains(planet_idx, terrain_idx) values (54, 30);
insert into planet_climates(planet_idx, climate_idx) values (54, 9);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (55, 'Skako', 27, 384, null, 1, null, 500000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (55, 37);
insert into planet_terrains(planet_idx, terrain_idx) values (55, 58);
insert into planet_climates(planet_idx, climate_idx) values (55, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (56, 'Muunilinst', 28, 412, 13800, 1, 25, 5000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (56, 36);
insert into planet_terrains(planet_idx, terrain_idx) values (56, 11);
insert into planet_terrains(planet_idx, terrain_idx) values (56, 38);
insert into planet_terrains(planet_idx, terrain_idx) values (56, 2);
insert into planet_climates(planet_idx, climate_idx) values (56, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (57, 'Shili', null, null, null, 1, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (57, 59);
insert into planet_terrains(planet_idx, terrain_idx) values (57, 60);
insert into planet_terrains(planet_idx, terrain_idx) values (57, 43);
insert into planet_terrains(planet_idx, terrain_idx) values (57, 36);
insert into planet_climates(planet_idx, climate_idx) values (57, 1);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (58, 'Kalee', 23, 378, 13850, 1, null, 4000000000);
insert into planet_terrains(planet_idx, terrain_idx) values (58, 4);
insert into planet_terrains(planet_idx, terrain_idx) values (58, 61);
insert into planet_terrains(planet_idx, terrain_idx) values (58, 23);
insert into planet_terrains(planet_idx, terrain_idx) values (58, 43);
insert into planet_climates(planet_idx, climate_idx) values (58, 5);
insert into planet_climates(planet_idx, climate_idx) values (58, 1);
insert into planet_climates(planet_idx, climate_idx) values (58, 2);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (59, 'Umbara', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (59, 45);
insert into planet_climates(planet_idx, climate_idx) values (59, 13);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (60, 'Tatooine', 23, 304, 10465, 1, 1, 200000);
insert into planet_terrains(planet_idx, terrain_idx) values (60, 18);
insert into planet_climates(planet_idx, climate_idx) values (60, 5);
insert into planets(id, planet_name, rotation_period, orbital_period, diameter, gravity, surface_water, population) values (61, 'Jakku', null, null, null, null, null, null);
insert into planet_terrains(planet_idx, terrain_idx) values (61, 46);
insert into planet_climates(planet_idx, climate_idx) values (61, 13);

alter sequence planet_id_seq restart with 62;
